version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FileProcessDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  db2:
    image: postgres:16
    container_name: postgres_db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DataBaseStorageDb 
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
volumes:
  pgdata:
  pgdata2:  